# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girasol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=200, verbose_name='Correo ó Teléfono')),
                ('email', models.BooleanField(default=False, verbose_name='Correo')),
                ('phone', models.BooleanField(default=False, verbose_name='Teléfono')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='posttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Post Translation'},
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=200, verbose_name='Autor'),
        ),
    ]
