# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 04:39
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('girasol', '0002_auto_20161114_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
