# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girasol', '0003_auto_20161121_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('slider', models.BooleanField(default=False, verbose_name='Slider')),
                ('posts', models.ManyToManyField(blank=True, null=True, to='girasol.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('image', models.ImageField(height_field='height', upload_to='imagenes/galerias', width_field='width')),
                ('galleries', models.ManyToManyField(blank=True, null=True, to='girasol.Gallery')),
            ],
        ),
    ]
