# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girasol', '0005_auto_20161122_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='galleries',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
