# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('girasol', '0006_auto_20161122_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('slider', models.BooleanField(default=False, verbose_name='Slider')),
                ('posts', models.ManyToManyField(blank=True, to='girasol.Post')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GalleryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='girasol.Gallery')),
            ],
            options={
                'default_permissions': (),
                'db_tablespace': '',
                'verbose_name': 'gallery Translation',
                'managed': True,
                'db_table': 'girasol_gallery_translation',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('image', models.ImageField(height_field='height', upload_to='imagenes/galerias', verbose_name='Imagen', width_field='width')),
                ('galleries', models.ManyToManyField(blank=True, to='girasol.Gallery')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PhotoTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='girasol.Photo')),
            ],
            options={
                'default_permissions': (),
                'db_tablespace': '',
                'verbose_name': 'photo Translation',
                'managed': True,
                'db_table': 'girasol_photo_translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='phototranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='gallerytranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
