# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girasol', '0007_auto_20161122_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='galleries',
            field=models.ManyToManyField(blank=True, to='girasol.Gallery'),
        ),
    ]
