# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-25 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girasol', '0008_auto_20161124_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Galería', 'verbose_name_plural': 'Galerías'},
        ),
        migrations.AlterModelOptions(
            name='gallerytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Galería Translation'},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'Información', 'verbose_name_plural': 'Informaciones'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
        migrations.AlterModelOptions(
            name='phototranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Imagen Translation'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
        migrations.AlterModelOptions(
            name='posttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Entrada Translation'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='galleries',
        ),
        migrations.AddField(
            model_name='gallery',
            name='photos',
            field=models.ManyToManyField(blank=True, to='girasol.Photo'),
        ),
        migrations.AddField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
