# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('girasol', '0010_post_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_link', models.TextField()),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LinkTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='girasol.Link')),
            ],
            options={
                'default_permissions': (),
                'managed': True,
                'verbose_name': 'Enlace Translation',
                'db_tablespace': '',
                'db_table': 'girasol_link_translation',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Frase',
                'verbose_name_plural': 'Frases',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuoteTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('quote', models.TextField()),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='girasol.Quote')),
            ],
            options={
                'default_permissions': (),
                'managed': True,
                'verbose_name': 'Frase Translation',
                'db_tablespace': '',
                'db_table': 'girasol_quote_translation',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='ext_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='footer_sec',
        ),
        migrations.RemoveField(
            model_name='post',
            name='main',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mission',
        ),
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.PositiveIntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='footer',
            field=models.BooleanField(default=True, verbose_name='Pie de página'),
        ),
        migrations.AlterField(
            model_name='post',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='_post_links_+', to='girasol.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.BooleanField(default=True, verbose_name='Menú'),
        ),
        migrations.AlterField(
            model_name='post',
            name='navigation',
            field=models.BooleanField(default=True, verbose_name='Navegación'),
        ),
        migrations.AlterField(
            model_name='post',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='girasol.Quote'),
        ),
        migrations.AlterUniqueTogether(
            name='quotetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='linktranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
