# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girasol', '0011_auto_20161208_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.PositiveIntegerField(blank=True, default=5, verbose_name='Prioridad'),
        ),
    ]
