# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girasol', '0013_auto_20161208_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='girasol.Quote'),
        ),
    ]
