# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girasol', '0014_auto_20161208_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='galleries',
        ),
        migrations.AddField(
            model_name='concept',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='girasol.Gallery'),
        ),
    ]
