# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girasol', '0016_auto_20161215_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['pk'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
    ]
