# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girasol', '0017_auto_20161219_1844'),
        ('girasol', '0017_auto_20161219_0601'),
    ]

    operations = [
    ]
