# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girasol', '0018_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['date'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
    ]
